In [2]:
import numpy as np

In [22]:
# Table : find the slicing
a: np.ndarray = np.arange(10, 30).reshape(4, 5)
print(a)

yellow = a[0][0]
blue = a[:,1::2]
green = a[0:3, 2]
purple = a[::2, -1]

print(f"yellow: {yellow}\n blue: {blue}\n green: {green}\n purple: {purple}")

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
yellow: 10
 blue: [[11 13]
 [16 18]
 [21 23]
 [26 28]]
 green: [12 17 22]
 purple: [14 24]


In [28]:
# 
a: np.ndarray = np.arange(0, 27).reshape((3, 3, 3))
print(a[1, 1, :])
print(a[:, 1, 0])
print(a[0, :, 2])

print(a)

[12 13 14]
[ 3 12 21]
[2 5 8]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [34]:
a = np.linspace(0, 2 * np.pi, 50)
print(a)
print("_____________________________________________________________________________\n")
print(np.sin(a))

[0.         0.12822827 0.25645654 0.38468481 0.51291309 0.64114136
 0.76936963 0.8975979  1.02582617 1.15405444 1.28228272 1.41051099
 1.53873926 1.66696753 1.7951958  1.92342407 2.05165235 2.17988062
 2.30810889 2.43633716 2.56456543 2.6927937  2.82102197 2.94925025
 3.07747852 3.20570679 3.33393506 3.46216333 3.5903916  3.71861988
 3.84684815 3.97507642 4.10330469 4.23153296 4.35976123 4.48798951
 4.61621778 4.74444605 4.87267432 5.00090259 5.12913086 5.25735913
 5.38558741 5.51381568 5.64204395 5.77027222 5.89850049 6.02672876
 6.15495704 6.28318531]
_____________________________________________________________________________

[ 0.00000000e+00  1.27877162e-01  2.53654584e-01  3.75267005e-01
  4.90717552e-01  5.98110530e-01  6.95682551e-01  7.81831482e-01
  8.55142763e-01  9.14412623e-01  9.58667853e-01  9.87181783e-01
  9.99486216e-01  9.95379113e-01  9.74927912e-01  9.38468422e-01
  8.86599306e-01  8.20172255e-01  7.40277997e-01  6.48228395e-01
  5.45534901e-01  4.33883739e-01  3.

In [71]:
# Masking
data: np.ndarray = np.arange(1, 101).reshape(10, 10)
print(data)
even_number_mask = data % 2 == 0

even = data[even_number_mask]
print(even)

copy = np.copy(even)
ends_with = np.where(print(str(copy)[-1] == "6"))
print(even[ends_with])

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
False
[]
